### PR TITLE
Adds functionality to find stations in a geographic area

### PR DESCRIPTION
**Pull request by adamhsparks**
Adds a new function, `find_stations_in()`, which can take a bounding box or a geospatial data set of polygon(s) and return stations either that fall within those boundaries or the station nearest the centroid(s).

This adds two new imports, {sf} (already installed with the {stars} import), and {osmdata} to derive a bounding box for a named place.

I've added full documentation including updating the vingettes and tests.

The vingettees have not yet been rebuilt due to this bug in {curl} https://github.com/jeroen/curl/issues/338#issuecomment-2121082003, but functionally the package is ready to go, I think.

### CODE REVIEW

**Comment by adamhsparks** [comment]
This PR also adds Max Moldovan (Uni Adelaide and part of AAGI) to the authors' list in recognition of his helpful and constructive suggestions and questions.

**Comment by adamhsparks** [comment]
Finally, I think it's passing all checks and the vignettes are rebuilt. This is ready for review and merging.

**Comment by adamhsparks** [comment]
I've spent some time with the vignettes in this PR as well, it's a bit messy with major additions and these edits but everything lines up and these additions necessitated changes to the vignettes, so it works out.

**Review by bozaah — APPROVED** [review]
Thanks @adamhsparks! Great addition with `find_stations_in()` and additional (tons of it!) work with the tests, re-doc and re-building of the vignettes. I have run the checks and everything works as expected.

**Pull request merged**
